#! /usr/bin/env python
# Name: ssuset.py
# Desc: SCIM Setup Utility - Set
# Date: 2011.03.25
# Note:

import sys
from stos.toolutil import *
import scim.ssu

#---macros---

#TOOL_NAME(string):
#The tool name. 
#This name would be used when creating a temporary directory.
TOOL_NAME='ssuset'

#TOOL_VERSION(string):
#Version information. Usually use the date of your last commit.
TOOL_VERSION='20110406'

#DEBUG_MODE(bool):
#True to enable debug mode(to show debug msg.), otherwise False.
DEBUG_MODE=False

#MSG_FILTER(msg_type bitwise expression):
#Don't show the messages unless the DEBUG_MODE is True if their type is
#listed in msg_type_list. Note that msg_type_list is an bitwise-expression
#of msg_type.
MSG_FILTER=MSG.ALL^MSG.NL

#ERR_STR(string): the string which is printed when an error occurs.
ERR_STR='ERR_SSUSET'

if __name__ == '__main__':
    tu=TuCore(TOOL_NAME,TOOL_VERSION,DEBUG_MODE,MSG_FILTER)

    def list_callback(opt,opt_str,value,parser,*args,**kwargs):
        scim.ssu.list(scim.ssu.ST.WRITE)
        tu.quit_tool(0)

    def version_callback(opt,opt_str,value,parser,*args,**kwargs):
        print tu.get_version()
        tu.quit_tool(0)

    def debug_callback(opt,opt_str,value,parser,*args,**kwargs):
        tu.set_debug_mode(True)

    def parse_options():
        tu.print_msg(MSG.DD,"---Function--- parse_options()")
        import optparse 
        #init options parser
        parser=optparse.OptionParser(description='''\
Set the value VALUE to the setting SETTING in the scim-setup-utils. \
If the assignment is successful, it prints the value, otherwise a string \
%s is printed.
            '''%ERR_STR,
            usage='%prog [OPTIONS] SETTING VALUE')
        parser.add_option('-l', '--list',
                          action='callback',
                          callback=list_callback,
                          help='display available settings and quit')
        parser.add_option('-V', '--version',
                          action='callback',
                          callback=version_callback,
                          help='display version information and quit')
        parser.add_option('-d', '--debug',
                          action='callback',
                          callback=debug_callback,
                          callback_args=('r',),
                          help='enable debug mode (Print the debug \
messages.)')
        (option, args)=parser.parse_args()
        tu.print_msg(MSG.DD,"option=[%r] args=[%r]" %(option,args))
        #check given arguments
        if len(args)==0:
            parser.print_help()
            tu.quit_tool(0)
        if len(args)==1:
            raise TuExcept(ERR.INPUT,
                "Invalid inputs: No VALUE is assigned.")
        if len(args)>2:
            raise TuExcept(ERR.INPUT,
                "Invalid inputs: Too many inputs.")
        tu.print_msg(MSG.DD,"SETTING=args=%r"%args)
        return args

    try:
        args=parse_options()
        if len(args)==2:
            # key, value
            tu.print_msg(MSG.DD,"ssu.set(%s,%s)"%(args[0],args[1]))
            print scim.ssu.set(args[0],args[1])
        else:
            pass
            # For now, imlist is not writeable
            # key, value, lang
            #print scim.ssu.get(args[0],args[1],args[2])
        tu.quit_tool(0)
    except TuExcept as e:
        tu.print_msg(MSG.EE,e.error_msg)
        tu.print_msg(MSG.NL,ERR_STR)
        tu.quit_tool(e.error_type)
    except Exception as e:
        tu.print_msg(MSG.EE,"Unknown exception: %r"%(e))
        tu.print_msg(MSG.NL,ERR_STR)
        tu.quit_tool(ERR.UNKNOWN)

